# Generated by Django 5.2.12 on 2026-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artworks/')),
                ('category', models.CharField(choices=[('Mehendi', 'Mehendi'), ('Painting', 'Painting'), ('Drawing', 'Drawing')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('event_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
